apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: pisang  # Tambahkan namespace di sini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: erwinhariadi/pisang_backend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "200Mi"