apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: pisang
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080  # Port pada container backend
  type: ClusterIP
