apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pisang  # Tambahkan namespace di sini
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: erwinhariadi/pisang_frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"