apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pisang
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # Port pada container frontend
  type: NodePort
