name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Pull LFS files (optional, if using LFS)
      - name: Pull LFS files
        run: git lfs pull

      # Set up Python environment for backend testing
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies for backend
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  docker-build-and-push:
    name: Build and Push Docker Images
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Hanya push saat di branch main

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image for Backend
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pisang_backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/pisang_backend:latest

      # Build and push Docker image for Frontend
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pisang_frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/pisang_frontend:latest
